version: "3.5"
services:

    php:
      image: litepubl/php70:latest
      container_name: ${FPM_CONTAINER_NAME}
      env_file: .env
      working_dir: /var/www/html
      volumes:
        - ..:/var/www/html
        - ./php/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
        - ${LOGS_DIR}:/logs
        - ssh:/root/.ssh
      depends_on:
        - postgres
        - mongo
      networks:
          # this network
          - default 
          # external network
          - second_default
      external_links:
        - ${EXTERNAL_NGINX}

    postgres:
      image: postgres:9.5
      container_name: ${POSTGRES_CONTAINER_NAME}
      env_file: .env
      ports:
        - ${POSTGRES_EXT_PORT}:5432
      working_dir: /var/www/html
      command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs -c client_min_messages=notice -c log_min_messages=warning -c log_min_error_statement=warning -c log_min_duration_statement=0 -c log_statement=all -c log_error_verbosity=default
      volumes:
        - ..:/var/www/html
        - db:/var/lib/postgresql/data
        - ${LOGS_DIR}:/logs

    mongo:
      image: mongo:latest
      container_name: ${MONGO_CONTAINER_NAME}
      ports:
      - ${MONGO_EXTERNAL_PORT}:27017
      volumes:
        - mongo:/data/db

    webserver:
      image: litepubl/nginx
      container_name: ${NGINX_CONTAINER_NAME}
      working_dir: /var/www/html
      volumes:
          - ..:/var/www/html
          - ${LOGS_DIR}:/var/log/nginx/
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - ${NGINX_EXT_PORT}:80
      depends_on:
        - php

volumes:
  ssh:
  db:
  mongo:

networks:
  default:
    driver: bridge
  second_default:
    external: true
